%% Funzione alpha dot dot per il blocco simulink
% Stefano Milantoni

function alpha_dd = dinamica_alpha(u, mm, mc, cm, cc, L, g)
% u = [alpha, alpha_dot, xc, xc_dot, Fc]'
    alpha_dot = u(1);
    alpha = u(2);
    xc_dot = u(3);
    Fc = u(4);

    alpha_dd = (mc * cm * sin(alpha) * xc_dot ...
                    - mm * sin(alpha) * cc * xc_dot ...
                    + mm^2 * L * sin(alpha) * cos(alpha) * alpha_dot^2  ...
                    + mm * sin(alpha) * Fc ...
                    + mm^2 * g * cos(alpha) ...
                    + mm * mc * g * cos(alpha) ...
                    - mc * cm * L * alpha_dot ...
                    - mm * cm * L * (cos(alpha))^2 * alpha_dot) ...
                   / ((mm * cos(alpha)^2 + mc) * mm * L);
end

% Struttura function:
%function resul_value = func_name(par1, par2)
%   ...
%   ...
%   resul_value = par1
%end